language: node_js
node_js:
    - "6.1.0"

branches:
    only:
        - "master"

before_install:
    - rm -f ./web-ext-artifacts/*.zip

script:
    - npm run build
    - npm run lint

before_deploy:
    - npm run update-version
    - npm run sign
